### ISSUE TITLE
[ui] Add popover component from explorer

### ISSUE THREAD

**Issue by aulneau** [leather-io/extension#398]
### Todo
- [ ] update to reflect active/hover colors
- [ ] allow icons to be passed to options
- [ ] allow sections within option list
  - [ ] section titles
- [ ] trigger icon button
- [ ] more robust placement settings

![Screen Shot 2020-05-29 at 9 42 47 AM](https://user-images.githubusercontent.com/11803153/83272479-cf176180-a190-11ea-9274-670100b19c33.png)
![Screen Shot 2020-05-29 at 9 42 59 AM](https://user-images.githubusercontent.com/11803153/83272481-cfaff800-a190-11ea-91cc-fe31bf2ea6b5.png)
